/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ricoh.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Usuario service. Represents a row in the &quot;USUARIO_Usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ricoh.model.impl.UsuarioModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ricoh.model.impl.UsuarioImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Usuario
 * @generated
 */
@ProviderType
public interface UsuarioModel extends BaseModel<Usuario> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a usuario model instance should use the {@link Usuario} interface instead.
	 */

	/**
	 * Returns the primary key of this usuario.
	 *
	 * @return the primary key of this usuario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this usuario.
	 *
	 * @param primaryKey the primary key of this usuario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this usuario.
	 *
	 * @return the uuid of this usuario
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this usuario.
	 *
	 * @param uuid the uuid of this usuario
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the usuario ID of this usuario.
	 *
	 * @return the usuario ID of this usuario
	 */
	public long getUsuarioId();

	/**
	 * Sets the usuario ID of this usuario.
	 *
	 * @param usuarioId the usuario ID of this usuario
	 */
	public void setUsuarioId(long usuarioId);

	/**
	 * Returns the create date of this usuario.
	 *
	 * @return the create date of this usuario
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this usuario.
	 *
	 * @param createDate the create date of this usuario
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the nombre of this usuario.
	 *
	 * @return the nombre of this usuario
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this usuario.
	 *
	 * @param nombre the nombre of this usuario
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the apellidos of this usuario.
	 *
	 * @return the apellidos of this usuario
	 */
	@AutoEscape
	public String getApellidos();

	/**
	 * Sets the apellidos of this usuario.
	 *
	 * @param apellidos the apellidos of this usuario
	 */
	public void setApellidos(String apellidos);

	/**
	 * Returns the correo of this usuario.
	 *
	 * @return the correo of this usuario
	 */
	@AutoEscape
	public String getCorreo();

	/**
	 * Sets the correo of this usuario.
	 *
	 * @param correo the correo of this usuario
	 */
	public void setCorreo(String correo);

	/**
	 * Returns the fecha_nac of this usuario.
	 *
	 * @return the fecha_nac of this usuario
	 */
	public Date getFecha_nac();

	/**
	 * Sets the fecha_nac of this usuario.
	 *
	 * @param fecha_nac the fecha_nac of this usuario
	 */
	public void setFecha_nac(Date fecha_nac);

	@Override
	public Usuario cloneWithOriginalValues();

}